export enum category {
  ADVICE = 'Advice',
  ANIMALS_AWWS = 'Animals & Awws',
  ANIME = 'Anime',
  ARTANDDESIGN = 'Art & Design',
  BEAUTY = 'Beauty',
  DIYANDHOME = 'Diy & Home',
  ENTERTAIMENT = 'Entertaiment',
  FASHION = 'Fashion',
  FINANCEANDBUSINESS = 'Finance & Business',
  FOOD = 'Food',
  FUNNY = 'Funny',
  GAMING = 'Gaming',
  HEALTHANDLIFESTYLE = 'Health & Lifestyle',
  HOBBIES = 'Hobbies',
  LIVESTREAMS = 'Livestreams',
  MUSIC = 'Music',
  NEWS = 'News',
  OUTDOORS = 'Outdoors',
  READINANDLITERATURE = 'Reading & Literature',
  RELATIONSHIPS = 'Relationships',
  EDUCATION = 'Education',
  SCIENCE = 'Science',
  SPORTS = 'Technology',
  TRAVEL = 'Travel',
  NATURE = 'Nature',
  JOB = 'Job',
}
